stocks = {'AALI.JK': 'Astra Agro Lestari Tbk. (AALI)',
 'ABBA.JK': 'Mahaka Media Tbk. (ABBA)',
 'ABDA.JK': 'Asuransi Bina Dana Arta Tbk. (ABDA)',
 'ABMM.JK': 'ABM Investama Tbk. (ABMM)',
 'ACES.JK': 'Ace Hardware Indonesia Tbk. (ACES)',
 'ACST.JK': 'Acset Indonusa Tbk. (ACST)',
 'ADES.JK': 'Akasha Wira International Tbk. (ADES)',
 'ADHI.JK': 'Adhi Karya (Persero) Tbk. (ADHI)',
 'ADMF.JK': 'Adira Dinamika Multi Finance T (ADMF)',
 'ADMG.JK': 'Polychem Indonesia Tbk (ADMG)',
 'ADRO.JK': 'Adaro Energy Tbk. (ADRO)',
 'AGAR.JK': 'Asia Sejahtera Mina Tbk. (AGAR)',
 'AGII.JK': 'Aneka Gas Industri Tbk. (AGII)',
 'AGRO.JK': 'Bank Raya Indonesia Tbk. (AGRO)',
 'AGRS.JK': 'Bank IBK Indonesia Tbk. (AGRS)',
 'AHAP.JK': 'Asuransi Harta Aman Pratama Tb (AHAP)',
 'AIMS.JK': 'Akbar Indo Makmur Stimec Tbk (AIMS)',
 'AISA.JK': 'FKS Food Sejahtera Tbk. (AISA)',
 'AKKU.JK': 'Anugerah Kagum Karya Utama Tbk (AKKU)',
 'AKPI.JK': 'Argha Karya Prima Industry Tbk (AKPI)',
 'AKRA.JK': 'AKR Corporindo Tbk. (AKRA)',
 'AKSI.JK': 'Maming Enam Sembilan Mineral T (AKSI)',
 'ALDO.JK': 'Alkindo Naratama Tbk. (ALDO)',
 'ALKA.JK': 'Alakasa Industrindo Tbk (ALKA)',
 'ALMI.JK': 'Alumindo Light Metal Industry (ALMI)',
 'ALTO.JK': 'Tri Banyan Tirta Tbk. (ALTO)',
 'AMAG.JK': 'Asuransi Multi Artha Guna Tbk. (AMAG)',
 'AMAN.JK': 'Makmur Berkah Amanda Tbk. (AMAN)',
 'AMAR.JK': 'Bank Amar Indonesia Tbk. (AMAR)',
 'AMFG.JK': 'Asahimas Flat Glass Tbk. (AMFG)',
 'AMIN.JK': 'Ateliers Mecaniques D Indonesi (AMIN)',
 'AMOR.JK': 'Ashmore Asset Management Indon (AMOR)',
 'AMRT.JK': 'Sumber Alfaria Trijaya Tbk. (AMRT)',
 'ANDI.JK': 'Andira Agro Tbk. (ANDI)',
 'ANJT.JK': 'Austindo Nusantara Jaya Tbk. (ANJT)',
 'ANTM.JK': 'Aneka Tambang Tbk. (ANTM)',
 'APEX.JK': 'Apexindo Pratama Duta Tbk. (APEX)',
 'APIC.JK': 'Pacific Strategic Financial Tb (APIC)',
 'APII.JK': 'Arita Prima Indonesia Tbk. (APII)',
 'APLI.JK': 'Asiaplast Industries Tbk. (APLI)',
 'APLN.JK': 'Agung Podomoro Land Tbk. (APLN)',
 'ARCI.JK': 'Archi Indonesia Tbk. (ARCI)',
 'ARGO.JK': 'Argo Pantes Tbk (ARGO)',
 'ARII.JK': 'Atlas Resources Tbk. (ARII)',
 'ARKA.JK': 'Arkha Jayanti Persada Tbk. (ARKA)',
 'ARMY.JK': 'Armidian Karyatama Tbk. (ARMY)',
 'ARNA.JK': 'Arwana Citramulia Tbk. (ARNA)',
 'ARTA.JK': 'Arthavest Tbk (ARTA)',
 'ARTI.JK': 'Ratu Prabu Energi Tbk (ARTI)',
 'ARTO.JK': 'Bank Jago Tbk. (ARTO)',
 'ASBI.JK': 'Asuransi Bintang Tbk. (ASBI)',
 'ASDM.JK': 'Asuransi Dayin Mitra Tbk. (ASDM)',
 'ASGR.JK': 'Astra Graphia Tbk. (ASGR)',
 'ASII.JK': 'Astra International Tbk. (ASII)',
 'ASJT.JK': 'Asuransi Jasa Tania Tbk. (ASJT)',
 'ASMI.JK': 'Asuransi Maximus Graha Persada (ASMI)',
 'ASPI.JK': 'Andalan Sakti Primaindo Tbk. (ASPI)',
 'ASRI.JK': 'Alam Sutera Realty Tbk. (ASRI)',
 'ASRM.JK': 'Asuransi Ramayana Tbk. (ASRM)',
 'ASSA.JK': 'Adi Sarana Armada Tbk. (ASSA)',
 'ATAP.JK': 'Trimitra Prawara Goldland Tbk. (ATAP)',
 'ATIC.JK': 'Anabatic Technologies Tbk. (ATIC)',
 'AUTO.JK': 'Astra Otoparts Tbk. (AUTO)',
 'AVIA.JK': 'Avia Avian Tbk. (AVIA)',
 'AYLS.JK': 'Agro Yasa Lestari Tbk. (AYLS)',
 'BABP.JK': 'Bank MNC Internasional Tbk. (BABP)',
 'BACA.JK': 'Bank Capital Indonesia Tbk. (BACA)',
 'BAJA.JK': 'Saranacentral Bajatama Tbk. (BAJA)',
 'BALI.JK': 'Bali Towerindo Sentra Tbk. (BALI)',
 'BANK.JK': 'Bank Aladin Syariah Tbk. (BANK)',
 'BAPA.JK': 'Bekasi Asri Pemula Tbk. (BAPA)',
 'BAPI.JK': 'Bhakti Agung Propertindo Tbk. (BAPI)',
 'BATA.JK': 'Sepatu Bata Tbk. (BATA)',
 'BAYU.JK': 'Bayu Buana Tbk (BAYU)',
 'BBCA.JK': 'Bank Central Asia Tbk. (BBCA)',
 'BBHI.JK': 'Allo Bank Indonesia Tbk. (BBHI)',
 'BBKP.JK': 'Bank KB Bukopin Tbk. (BBKP)',
 'BBLD.JK': 'Buana Finance Tbk. (BBLD)',
 'BBMD.JK': 'Bank Mestika Dharma Tbk. (BBMD)',
 'BBNI.JK': 'Bank Negara Indonesia (BBNI)',
 'BBRI.JK': 'Bank Rakyat Indonesia (BBRI)',
 'BBRM.JK': 'Pelayaran Nasional Bina Buana (BBRM)',
 'BBSI.JK': 'Bank Bisnis Internasional Tbk. (BBSI)',
 'BBSS.JK': 'Bumi Benowo Sukses Sejahtera T (BBSS)',
 'BBTN.JK': 'Bank Tabungan Negara (Persero) (BBTN)',
 'BBYB.JK': 'Bank Neo Commerce Tbk. (BBYB)',
 'BCAP.JK': 'MNC Kapital Indonesia Tbk. (BCAP)',
 'BCIC.JK': 'Bank JTrust Indonesia Tbk. (BCIC)',
 'BCIP.JK': 'Bumi Citra Permai Tbk. (BCIP)',
 'BDMN.JK': 'Bank Danamon Indonesia Tbk. (BDMN)',
 'BEBS.JK': 'Berkah Beton Sadaya Tbk. (BEBS)',
 'BEEF.JK': 'Estika Tata Tiara Tbk. (BEEF)',
 'BEKS.JK': 'Bank Pembangunan Daerah Banten (BEKS)',
 'BELL.JK': 'Trisula Textile Industries Tbk (BELL)',
 'BESS.JK': 'Batulicin Nusantara Maritim Tb (BESS)',
 'BEST.JK': 'Bekasi Fajar Industrial Estate (BEST)',
 'BFIN.JK': 'BFI Finance Indonesia Tbk. (BFIN)',
 'BGTG.JK': 'Bank Ganesha Tbk. (BGTG)',
 'BHAT.JK': 'Bhakti Multi Artha Tbk. (BHAT)',
 'BHIT.JK': 'MNC Investama Tbk. (BHIT)',
 'BIKA.JK': 'Binakarya Jaya Abadi Tbk. (BIKA)',
 'BIMA.JK': 'Primarindo Asia Infrastructure (BIMA)',
 'BINA.JK': 'Bank Ina Perdana Tbk. (BINA)',
 'BINO.JK': 'Perma Plasindo Tbk. (BINO)',
 'BIPI.JK': 'Astrindo Nusantara Infrastrukt (BIPI)',
 'BIPP.JK': 'Bhuwanatala Indah Permai Tbk. (BIPP)',
 'BIRD.JK': 'Blue Bird Tbk. (BIRD)',
 'BISI.JK': 'BISI International Tbk. (BISI)',
 'BJBR.JK': 'Bank Pembangunan Daerah Jawa B (BJBR)',
 'BJTM.JK': 'Bank Pembangunan Daerah Jawa T (BJTM)',
 'BKDP.JK': 'Bukit Darmo Property Tbk (BKDP)',
 'BKSL.JK': 'Sentul City Tbk. (BKSL)',
 'BKSW.JK': 'Bank QNB Indonesia Tbk. (BKSW)',
 'BLTA.JK': 'Berlian Laju Tanker Tbk (BLTA)',
 'BLTZ.JK': 'Graha Layar Prima Tbk. (BLTZ)',
 'BLUE.JK': 'Berkah Prima Perkasa Tbk. (BLUE)',
 'BMAS.JK': 'Bank Maspion Indonesia Tbk. (BMAS)',
 'BMHS.JK': 'Bundamedik Tbk. (BMHS)',
 'BMRI.JK': 'Bank Mandiri (Persero) Tbk. (BMRI)',
 'BMSR.JK': 'Bintang Mitra Semestaraya Tbk (BMSR)',
 'BMTR.JK': 'Global Mediacom Tbk. (BMTR)',
 'BNBA.JK': 'Bank Bumi Arta Tbk. (BNBA)',
 'BNBR.JK': 'Bakrie & Brothers Tbk (BNBR)',
 'BNGA.JK': 'Bank CIMB Niaga Tbk. (BNGA)',
 'BNII.JK': 'Bank Maybank Indonesia Tbk. (BNII)',
 'BNLI.JK': 'Bank Permata Tbk. (BNLI)',
 'BOBA.JK': 'Formosa Ingredient Factory Tbk (BOBA)',
 'BOGA.JK': 'Bintang Oto Global Tbk. (BOGA)',
 'BOLA.JK': 'Bali Bintang Sejahtera Tbk. (BOLA)',
 'BOLT.JK': 'Garuda Metalindo Tbk. (BOLT)',
 'BOSS.JK': 'Borneo Olah Sarana Sukses Tbk. (BOSS)',
 'BPFI.JK': 'Batavia Prosperindo Finance Tb (BPFI)',
 'BPII.JK': 'Batavia Prosperindo Internasio (BPII)',
 'BPTR.JK': 'Batavia Prosperindo Trans Tbk. (BPTR)',
 'BRAM.JK': 'Indo Kordsa Tbk. (BRAM)',
 'BRIS.JK': 'Bank Syariah Indonesia Tbk. (BRIS)',
 'BRMS.JK': 'Bumi Resources Minerals Tbk. (BRMS)',
 'BRNA.JK': 'Berlina Tbk. (BRNA)',
 'BRPT.JK': 'Barito Pacific Tbk. (BRPT)',
 'BSDE.JK': 'Bumi Serpong Damai Tbk. (BSDE)',
 'BSIM.JK': 'Bank Sinarmas Tbk. (BSIM)',
 'BSML.JK': 'Bintang Samudera Mandiri Lines (BSML)',
 'BSSR.JK': 'Baramulti Suksessarana Tbk. (BSSR)',
 'BSWD.JK': 'Bank Of India Indonesia Tbk. (BSWD)',
 'BTEK.JK': 'Bumi Teknokultura Unggul Tbk (BTEK)',
 'BTEL.JK': 'Bakrie Telecom Tbk. (BTEL)',
 'BTON.JK': 'Betonjaya Manunggal Tbk. (BTON)',
 'BTPN.JK': 'Bank BTPN Tbk. (BTPN)',
 'BTPS.JK': 'Bank BTPN Syariah Tbk. (BTPS)',
 'BUDI.JK': 'Budi Starch & Sweetener Tbk. (BUDI)',
 'BUKA.JK': 'Bukalapak.com Tbk. (BUKA)',
 'BUKK.JK': 'Bukaka Teknik Utama Tbk. (BUKK)',
 'BULL.JK': 'Buana Lintas Lautan Tbk. (BULL)',
 'BUMI.JK': 'Bumi Resources Tbk. (BUMI)',
 'BUVA.JK': 'Bukit Uluwatu Villa Tbk. (BUVA)',
 'BVIC.JK': 'Bank Victoria International Tb (BVIC)',
 'BWPT.JK': 'Eagle High Plantations Tbk. (BWPT)',
 'BYAN.JK': 'Bayan Resources Tbk. (BYAN)',
 'CAKK.JK': 'Cahayaputra Asa Keramik Tbk. (CAKK)',
 'CAMP.JK': 'Campina Ice Cream Industry Tbk (CAMP)',
 'CANI.JK': 'Capitol Nusantara Indonesia Tb (CANI)',
 'CARE.JK': 'Metro Healthcare Indonesia Tbk (CARE)',
 'CARS.JK': 'Industri dan Perdagangan Bintr (CARS)',
 'CASA.JK': 'Capital Financial Indonesia Tb (CASA)',
 'CASH.JK': 'Cashlez Worldwide Indonesia Tb (CASH)',
 'CASS.JK': 'Cardig Aero Services Tbk. (CASS)',
 'CBMF.JK': 'Cahaya Bintang Medan Tbk. (CBMF)',
 'CCSI.JK': 'Communication Cable Systems In (CCSI)',
 'CEKA.JK': 'Wilmar Cahaya Indonesia Tbk. (CEKA)',
 'CENT.JK': 'Centratama Telekomunikasi Indo (CENT)',
 'CFIN.JK': 'Clipan Finance Indonesia Tbk. (CFIN)',
 'CINT.JK': 'Chitose Internasional Tbk. (CINT)',
 'CITA.JK': 'Cita Mineral Investindo Tbk. (CITA)',
 'CITY.JK': 'Natura City Developments Tbk. (CITY)',
 'CLAY.JK': 'Citra Putra Realty Tbk. (CLAY)',
 'CLEO.JK': 'Sariguna Primatirta Tbk. (CLEO)',
 'CLPI.JK': 'Colorpak Indonesia Tbk. (CLPI)',
 'CMNP.JK': 'Citra Marga Nusaphala Persada (CMNP)',
 'CMNT.JK': 'Cemindo Gemilang Tbk. (CMNT)',
 'CMPP.JK': 'AirAsia Indonesia Tbk. (CMPP)',
 'CMRY.JK': 'Cisarua Mountain Dairy Tbk. (CMRY)',
 'CNKO.JK': 'Exploitasi Energi Indonesia Tb (CNKO)',
 'CNTX.JK': 'Century Textile Industry Tbk. (CNTX)',
 'COCO.JK': 'Wahana Interfood Nusantara Tbk (COCO)',
 'COWL.JK': 'Cowell Development Tbk. (COWL)',
 'CPIN.JK': 'Charoen Pokphand Indonesia Tbk (CPIN)',
 'CPRI.JK': 'Capri Nusa Satu Properti Tbk. (CPRI)',
 'CPRO.JK': 'Central Proteina Prima Tbk. (CPRO)',
 'CSAP.JK': 'Catur Sentosa Adiprana Tbk. (CSAP)',
 'CSIS.JK': 'Cahayasakti Investindo Sukses (CSIS)',
 'CSMI.JK': 'Cipta Selera Murni Tbk. (CSMI)',
 'CSRA.JK': 'Cisadane Sawit Raya Tbk. (CSRA)',
 'CTBN.JK': 'Citra Tubindo Tbk. (CTBN)',
 'CTRA.JK': 'Ciputra Development Tbk. (CTRA)',
 'CTTH.JK': 'Citatah Tbk. (CTTH)',
 'DADA.JK': 'Diamond Citra Propertindo Tbk. (DADA)',
 'DART.JK': 'Duta Anggada Realty Tbk. (DART)',
 'DAYA.JK': 'Duta Intidaya Tbk. (DAYA)',
 'DCII.JK': 'DCI Indonesia Tbk. (DCII)',
 'DEAL.JK': 'Dewata Freightinternational Tb (DEAL)',
 'DEFI.JK': 'Danasupra Erapacific Tbk. (DEFI)',
 'DEPO.JK': 'Caturkarda Depo Bangunan Tbk. (DEPO)',
 'DEWA.JK': 'Darma Henwa Tbk (DEWA)',
 'DFAM.JK': 'Dafam Property Indonesia Tbk. (DFAM)',
 'DGIK.JK': 'Nusa Konstruksi Enjiniring Tbk (DGIK)',
 'DGNS.JK': 'Diagnos Laboratorium Utama Tbk (DGNS)',
 'DIGI.JK': 'Arkadia Digital Media Tbk. (DIGI)',
 'DILD.JK': 'Intiland Development Tbk. (DILD)',
 'DIVA.JK': 'Distribusi Voucher Nusantara T (DIVA)',
 'DKFT.JK': 'Central Omega Resources Tbk. (DKFT)',
 'DLTA.JK': 'Delta Djakarta Tbk. (DLTA)',
 'DMAS.JK': 'Puradelta Lestari Tbk. (DMAS)',
 'DMMX.JK': 'Digital Mediatama Maxima Tbk. (DMMX)',
 'DMND.JK': 'Diamond Food Indonesia Tbk. (DMND)',
 'DNAR.JK': 'Bank Oke Indonesia Tbk. (DNAR)',
 'DNET.JK': 'Indoritel Makmur Internasional (DNET)',
 'DOID.JK': 'Delta Dunia Makmur Tbk. (DOID)',
 'DPNS.JK': 'Duta Pertiwi Nusantara Tbk. (DPNS)',
 'DPUM.JK': 'Dua Putra Utama Makmur Tbk. (DPUM)',
 'DSFI.JK': 'Dharma Samudera Fishing Indust (DSFI)',
 'DSNG.JK': 'Dharma Satya Nusantara Tbk. (DSNG)',
 'DSSA.JK': 'Dian Swastatika Sentosa Tbk (DSSA)',
 'DUCK.JK': 'Jaya Bersama Indo Tbk. (DUCK)',
 'DUTI.JK': 'Duta Pertiwi Tbk (DUTI)',
 'DVLA.JK': 'Darya-Varia Laboratoria Tbk. (DVLA)',
 'DWGL.JK': 'Dwi Guna Laksana Tbk. (DWGL)',
 'DYAN.JK': 'Dyandra Media International Tb (DYAN)',
 'EAST.JK': 'Eastparc Hotel Tbk. (EAST)',
 'ECII.JK': 'Electronic City Indonesia Tbk. (ECII)',
 'EDGE.JK': 'Indointernet Tbk. (EDGE)',
 'EKAD.JK': 'Ekadharma International Tbk. (EKAD)',
 'ELSA.JK': 'Elnusa Tbk. (ELSA)',
 'ELTY.JK': 'Bakrieland Development Tbk. (ELTY)',
 'EMDE.JK': 'Megapolitan Developments Tbk. (EMDE)',
 'EMTK.JK': 'Elang Mahkota Teknologi Tbk. (EMTK)',
 'ENRG.JK': 'Energi Mega Persada Tbk. (ENRG)',
 'ENVY.JK': 'Envy Technologies Indonesia Tb (ENVY)',
 'ENZO.JK': 'Morenzo Abadi Perkasa Tbk. (ENZO)',
 'EPAC.JK': 'Megalestari Epack Sentosaraya (EPAC)',
 'EPMT.JK': 'Enseval Putera Megatrading Tbk (EPMT)',
 'ERAA.JK': 'Erajaya Swasembada Tbk. (ERAA)',
 'ERTX.JK': 'Eratex Djaja Tbk. (ERTX)',
 'ESIP.JK': 'Sinergi Inti Plastindo Tbk. (ESIP)',
 'ESSA.JK': 'Surya Esa Perkasa Tbk. (ESSA)',
 'ESTA.JK': 'Esta Multi Usaha Tbk. (ESTA)',
 'ESTI.JK': 'Ever Shine Tex Tbk. (ESTI)',
 'ETWA.JK': 'Eterindo Wahanatama Tbk (ETWA)',
 'EXCL.JK': 'XL Axiata Tbk. (EXCL)',
 'FAPA.JK': 'FAP Agri Tbk. (FAPA)',
 'FAST.JK': 'Fast Food Indonesia Tbk. (FAST)',
 'FASW.JK': 'Fajar Surya Wisesa Tbk. (FASW)',
 'FILM.JK': 'MD Pictures Tbk. (FILM)',
 'FIMP.JK': 'Fimperkasa Utama Tbk. (FIMP)',
 'FIRE.JK': 'Alfa Energi Investama Tbk. (FIRE)',
 'FISH.JK': 'FKS Multi Agro Tbk. (FISH)',
 'FITT.JK': 'Hotel Fitra International Tbk. (FITT)',
 'FLMC.JK': 'Falmaco Nonwoven Industri Tbk. (FLMC)',
 'FMII.JK': 'Fortune Mate Indonesia Tbk (FMII)',
 'FOOD.JK': 'Sentra Food Indonesia Tbk. (FOOD)',
 'FORU.JK': 'Fortune Indonesia Tbk (FORU)',
 'FORZ.JK': 'Forza Land Indonesia Tbk. (FORZ)',
 'FPNI.JK': 'Lotte Chemical Titan Tbk. (FPNI)',
 'FREN.JK': 'Smartfren Telecom Tbk. (FREN)',
 'FUJI.JK': 'Fuji Finance Indonesia Tbk. (FUJI)',
 'GAMA.JK': 'Aksara Global Development Tbk. (GAMA)',
 'GDST.JK': 'Gunawan Dianjaya Steel Tbk. (GDST)',
 'GDYR.JK': 'Goodyear Indonesia Tbk. (GDYR)',
 'GEMA.JK': 'Gema Grahasarana Tbk. (GEMA)',
 'GEMS.JK': 'Golden Energy Mines Tbk. (GEMS)',
 'GGRM.JK': 'Gudang Garam Tbk. (GGRM)',
 'GGRP.JK': 'Gunung Raja Paksi Tbk. (GGRP)',
 'GHON.JK': 'Gihon Telekomunikasi Indonesia (GHON)',
 'GIAA.JK': 'Garuda Indonesia (Persero) Tbk (GIAA)',
 'GJTL.JK': 'Gajah Tunggal Tbk. (GJTL)',
 'GLOB.JK': 'Globe Kita Terang Tbk. (GLOB)',
 'GLVA.JK': 'Galva Technologies Tbk. (GLVA)',
 'GMFI.JK': 'Garuda Maintenance Facility Ae (GMFI)',
 'GMTD.JK': 'Gowa Makassar Tourism Developm (GMTD)',
 'GOLD.JK': 'Visi Telekomunikasi Infrastruk (GOLD)',
 'GOLL.JK': 'Golden Plantation Tbk. (GOLL)',
 'GOOD.JK': 'Garudafood Putra Putri Jaya Tb (GOOD)',
 'GPRA.JK': 'Perdana Gapuraprima Tbk. (GPRA)',
 'GPSO.JK': 'Geoprima Solusi Tbk. (GPSO)',
 'GSMF.JK': 'Equity Development Investment (GSMF)',
 'GTBO.JK': 'Garda Tujuh Buana Tbk (GTBO)',
 'GTSI.JK': 'GTS Internasional Tbk. (GTSI)',
 'GWSA.JK': 'Greenwood Sejahtera Tbk. (GWSA)',
 'GZCO.JK': 'Gozco Plantations Tbk. (GZCO)',
 'HADE.JK': 'Himalaya Energi Perkasa Tbk. (HADE)',
 'HAIS.JK': 'Hasnur Internasional Shipping (HAIS)',
 'HDFA.JK': 'Radana Bhaskara Finance Tbk. (HDFA)',
 'HDIT.JK': 'Hensel Davest Indonesia Tbk. (HDIT)',
 'HDTX.JK': 'Panasia Indo Resources Tbk. (HDTX)',
 'HEAL.JK': 'Medikaloka Hermina Tbk. (HEAL)',
 'HELI.JK': 'Jaya Trishindo Tbk. (HELI)',
 'HERO.JK': 'Hero Supermarket Tbk. (HERO)',
 'HEXA.JK': 'Hexindo Adiperkasa Tbk. (HEXA)',
 'HITS.JK': 'Humpuss Intermoda Transportasi (HITS)',
 'HKMU.JK': 'HK Metals Utama Tbk. (HKMU)',
 'HMSP.JK': 'H.M. Sampoerna Tbk. (HMSP)',
 'HOKI.JK': 'Buyung Poetra Sembada Tbk. (HOKI)',
 'HOME.JK': 'Hotel Mandarine Regency Tbk. (HOME)',
 'HOMI.JK': 'Grand House Mulia Tbk. (HOMI)',
 'HOPE.JK': 'Harapan Duta Pertiwi Tbk. (HOPE)',
 'HOTL.JK': 'Saraswati Griya Lestari Tbk. (HOTL)',
 'HRME.JK': 'Menteng Heritage Realty Tbk. (HRME)',
 'HRTA.JK': 'Hartadinata Abadi Tbk. (HRTA)',
 'HRUM.JK': 'Harum Energy Tbk. (HRUM)',
 'IATA.JK': 'Indonesia Transport & Infrastr (IATA)',
 'IBFN.JK': 'Intan Baruprana Finance Tbk. (IBFN)',
 'IBST.JK': 'Inti Bangun Sejahtera Tbk. (IBST)',
 'ICBP.JK': 'Indofood CBP Sukses Makmur Tbk (ICBP)',
 'ICON.JK': 'Island Concepts Indonesia Tbk. (ICON)',
 'IDEA.JK': 'Idea Indonesia Akademi Tbk. (IDEA)',
 'IDPR.JK': 'Indonesia Pondasi Raya Tbk. (IDPR)',
 'IFII.JK': 'Indonesia Fibreboard Industry (IFII)',
 'IFSH.JK': 'Ifishdeco Tbk. (IFSH)',
 'IGAR.JK': 'Champion Pacific Indonesia Tbk (IGAR)',
 'IIKP.JK': 'Inti Agri Resources Tbk (IIKP)',
 'IKAI.JK': 'Intikeramik Alamasri Industri (IKAI)',
 'IKAN.JK': 'Era Mandiri Cemerlang Tbk. (IKAN)',
 'IKBI.JK': 'Sumi Indo Kabel Tbk. (IKBI)',
 'IMAS.JK': 'Indomobil Sukses Internasional (IMAS)',
 'IMJS.JK': 'Indomobil Multi Jasa Tbk. (IMJS)',
 'IMPC.JK': 'Impack Pratama Industri Tbk. (IMPC)',
 'INAF.JK': 'Indofarma Tbk. (INAF)',
 'INAI.JK': 'Indal Aluminium Industry Tbk. (INAI)',
 'INCF.JK': 'Indo Komoditi Korpora Tbk. (INCF)',
 'INCI.JK': 'Intanwijaya Internasional Tbk (INCI)',
 'INCO.JK': 'Vale Indonesia Tbk. (INCO)',
 'INDF.JK': 'Indofood Sukses Makmur Tbk. (INDF)',
 'INDO.JK': 'Royalindo Investa Wijaya Tbk. (INDO)',
 'INDR.JK': 'Indo-Rama Synthetics Tbk. (INDR)',
 'INDS.JK': 'Indospring Tbk. (INDS)',
 'INDX.JK': 'Tanah Laut Tbk (INDX)',
 'INDY.JK': 'Indika Energy Tbk. (INDY)',
 'INKP.JK': 'Indah Kiat Pulp & Paper Tbk. (INKP)',
 'INOV.JK': 'Inocycle Technology Group Tbk. (INOV)',
 'INPC.JK': 'Bank Artha Graha Internasional (INPC)',
 'INPP.JK': 'Indonesian Paradise Property T (INPP)',
 'INPS.JK': 'Indah Prakasa Sentosa Tbk. (INPS)',
 'INRU.JK': 'Toba Pulp Lestari Tbk. (INRU)',
 'INTA.JK': 'Intraco Penta Tbk. (INTA)',
 'INTD.JK': 'Inter Delta Tbk (INTD)',
 'INTP.JK': 'Indocement Tunggal Prakarsa Tb (INTP)',
 'IPAC.JK': 'Era Graharealty Tbk. (IPAC)',
 'IPCC.JK': 'Indonesia Kendaraan Terminal T (IPCC)',
 'IPCM.JK': 'Jasa Armada Indonesia Tbk. (IPCM)',
 'IPOL.JK': 'Indopoly Swakarsa Industry Tbk (IPOL)',
 'IPPE.JK': 'Indo Pureco Pratama Tbk. (IPPE)',
 'IPTV.JK': 'MNC Vision Networks Tbk. (IPTV)',
 'IRRA.JK': 'Itama Ranoraya Tbk. (IRRA)',
 'ISAT.JK': 'Indosat Tbk. (ISAT)',
 'ISSP.JK': 'Steel Pipe Industry of Indones (ISSP)',
 'ITIC.JK': 'Indonesian Tobacco Tbk. (ITIC)',
 'ITMA.JK': 'Sumber Energi Andalan Tbk. (ITMA)',
 'ITMG.JK': 'Indo Tambangraya Megah Tbk. (ITMG)',
 'JAST.JK': 'Jasnita Telekomindo Tbk. (JAST)',
 'JAWA.JK': 'Jaya Agra Wattie Tbk. (JAWA)',
 'JAYA.JK': 'Armada Berjaya Trans Tbk. (JAYA)',
 'JECC.JK': 'Jembo Cable Company Tbk. (JECC)',
 'JGLE.JK': 'Graha Andrasentra Propertindo (JGLE)',
 'JIHD.JK': 'Jakarta International Hotels & (JIHD)',
 'JKON.JK': 'Jaya Konstruksi Manggala Prata (JKON)',
 'JKSW.JK': 'Jakarta Kyoei Steel Works Tbk. (JKSW)',
 'JMAS.JK': 'Asuransi Jiwa Syariah Jasa Mit (JMAS)',
 'JPFA.JK': 'Japfa Comfeed Indonesia Tbk. (JPFA)',
 'JRPT.JK': 'Jaya Real Property Tbk. (JRPT)',
 'JSKY.JK': 'Sky Energy Indonesia Tbk. (JSKY)',
 'JSMR.JK': 'Jasa Marga (Persero) Tbk. (JSMR)',
 'JSPT.JK': 'Jakarta Setiabudi Internasiona (JSPT)',
 'JTPE.JK': 'Jasuindo Tiga Perkasa Tbk. (JTPE)',
 'KAEF.JK': 'Kimia Farma Tbk. (KAEF)',
 'KARW.JK': 'ICTSI Jasa Prima Tbk. (KARW)',
 'KAYU.JK': 'Darmi Bersaudara Tbk. (KAYU)',
 'KBAG.JK': 'Karya Bersama Anugerah Tbk. (KBAG)',
 'KBLI.JK': 'KMI Wire & Cable Tbk. (KBLI)',
 'KBLM.JK': 'Kabelindo Murni Tbk. (KBLM)',
 'KBLV.JK': 'First Media Tbk. (KBLV)',
 'KBRI.JK': 'Kertas Basuki Rachmat Indonesi (KBRI)',
 'KDSI.JK': 'Kedawung Setia Industrial Tbk. (KDSI)',
 'KEEN.JK': 'Kencana Energi Lestari Tbk. (KEEN)',
 'KEJU.JK': 'Mulia Boga Raya Tbk. (KEJU)',
 'KIAS.JK': 'Keramika Indonesia Assosiasi T (KIAS)',
 'KICI.JK': 'Kedaung Indah Can Tbk (KICI)',
 'KIJA.JK': 'Kawasan Industri Jababeka Tbk. (KIJA)',
 'KINO.JK': 'Kino Indonesia Tbk. (KINO)',
 'KIOS.JK': 'Kioson Komersial Indonesia Tbk (KIOS)',
 'KJEN.JK': 'Krida Jaringan Nusantara Tbk. (KJEN)',
 'KKGI.JK': 'Resource Alam Indonesia Tbk. (KKGI)',
 'KLBF.JK': 'Kalbe Farma Tbk. (KLBF)',
 'KMDS.JK': 'Kurniamitra Duta Sentosa Tbk. (KMDS)',
 'KMTR.JK': 'Kirana Megatara Tbk. (KMTR)',
 'KOBX.JK': 'Kobexindo Tractors Tbk. (KOBX)',
 'KOIN.JK': 'Kokoh Inti Arebama Tbk (KOIN)',
 'KONI.JK': 'Perdana Bangun Pusaka Tbk (KONI)',
 'KOPI.JK': 'Mitra Energi Persada Tbk. (KOPI)',
 'KOTA.JK': 'DMS Propertindo Tbk. (KOTA)',
 'KPAL.JK': 'Steadfast Marine Tbk. (KPAL)',
 'KPAS.JK': 'Cottonindo Ariesta Tbk. (KPAS)',
 'KPIG.JK': 'MNC Land Tbk. (KPIG)',
 'KRAH.JK': 'Grand Kartech Tbk. (KRAH)',
 'KRAS.JK': 'Krakatau Steel (Persero) Tbk. (KRAS)',
 'KREN.JK': 'Kresna Graha Investama Tbk. (KREN)',
 'KUAS.JK': 'Ace Oldfields Tbk. (KUAS)',
 'LABA.JK': 'Ladangbaja Murni Tbk. (LABA)',
 'LAND.JK': 'Trimitra Propertindo Tbk. (LAND)',
 'LAPD.JK': 'Leyand International Tbk. (LAPD)',
 'LCGP.JK': 'Eureka Prima Jakarta Tbk. (LCGP)',
 'LCKM.JK': 'LCK Global Kedaton Tbk. (LCKM)',
 'LEAD.JK': 'Logindo Samudramakmur Tbk. (LEAD)',
 'LFLO.JK': 'Imago Mulia Persada Tbk. (LFLO)',
 'LIFE.JK': 'Asuransi Jiwa Sinarmas MSIG Tb (LIFE)',
 'LINK.JK': 'Link Net Tbk. (LINK)',
 'LION.JK': 'Lion Metal Works Tbk. (LION)',
 'LMAS.JK': 'Limas Indonesia Makmur Tbk (LMAS)',
 'LMPI.JK': 'Langgeng Makmur Industri Tbk. (LMPI)',
 'LMSH.JK': 'Lionmesh Prima Tbk. (LMSH)',
 'LPCK.JK': 'Lippo Cikarang Tbk (LPCK)',
 'LPGI.JK': 'Lippo General Insurance Tbk. (LPGI)',
 'LPIN.JK': 'Multi Prima Sejahtera Tbk (LPIN)',
 'LPKR.JK': 'Lippo Karawaci Tbk. (LPKR)',
 'LPLI.JK': 'Star Pacific Tbk (LPLI)',
 'LPPF.JK': 'Matahari Department Store Tbk. (LPPF)',
 'LPPS.JK': 'Lenox Pasifik Investama Tbk. (LPPS)',
 'LRNA.JK': 'Eka Sari Lorena Transport Tbk. (LRNA)',
 'LSIP.JK': 'PP London Sumatra Indonesia Tb (LSIP)',
 'LTLS.JK': 'Lautan Luas Tbk. (LTLS)',
 'LUCK.JK': 'Sentral Mitra Informatika Tbk. (LUCK)',
 'LUCY.JK': 'Lima Dua Lima Tiga Tbk. (LUCY)',
 'MABA.JK': 'Marga Abhinaya Abadi Tbk. (MABA)',
 'MAGP.JK': 'Multi Agro Gemilang Plantation (MAGP)',
 'MAIN.JK': 'Malindo Feedmill Tbk. (MAIN)',
 'MAMI.JK': 'Mas Murni Indonesia Tbk (MAMI)',
 'MAPA.JK': 'Map Aktif Adiperkasa Tbk. (MAPA)',
 'MAPB.JK': 'MAP Boga Adiperkasa Tbk. (MAPB)',
 'MAPI.JK': 'Mitra Adiperkasa Tbk. (MAPI)',
 'MARI.JK': 'Mahaka Radio Integra Tbk. (MARI)',
 'MARK.JK': 'Mark Dynamics Indonesia Tbk. (MARK)',
 'MASA.JK': 'Multistrada Arah Sarana Tbk. (MASA)',
 'MASB.JK': 'Bank Multiarta Sentosa Tbk. (MASB)',
 'MAYA.JK': 'Bank Mayapada Internasional Tb (MAYA)',
 'MBAP.JK': 'Mitrabara Adiperdana Tbk. (MBAP)',
 'MBSS.JK': 'Mitrabahtera Segara Sejati Tbk (MBSS)',
 'MBTO.JK': 'Martina Berto Tbk. (MBTO)',
 'MCAS.JK': 'M Cash Integrasi Tbk. (MCAS)',
 'MCOL.JK': 'Prima Andalan Mandiri Tbk. (MCOL)',
 'MCOR.JK': 'Bank China Construction Bank I (MCOR)',
 'MDIA.JK': 'Intermedia Capital Tbk. (MDIA)',
 'MDKA.JK': 'Merdeka Copper Gold Tbk. (MDKA)',
 'MDKI.JK': 'Emdeki Utama Tbk. (MDKI)',
 'MDLN.JK': 'Modernland Realty Tbk. (MDLN)',
 'MDRN.JK': 'Modern Internasional Tbk. (MDRN)',
 'MEDC.JK': 'Medco Energi Internasional Tbk (MEDC)',
 'MEGA.JK': 'Bank Mega Tbk. (MEGA)',
 'MERK.JK': 'Merck Tbk. (MERK)',
 'META.JK': 'Nusantara Infrastructure Tbk. (META)',
 'MFIN.JK': 'Mandala Multifinance Tbk. (MFIN)',
 'MFMI.JK': 'Multifiling Mitra Indonesia Tb (MFMI)',
 'MGLV.JK': 'Panca Anugrah Wisesa Tbk. (MGLV)',
 'MGNA.JK': 'Magna Investama Mandiri Tbk. (MGNA)',
 'MGRO.JK': 'Mahkota Group Tbk. (MGRO)',
 'MICE.JK': 'Multi Indocitra Tbk. (MICE)',
 'MIDI.JK': 'Midi Utama Indonesia Tbk. (MIDI)',
 'MIKA.JK': 'Mitra Keluarga Karyasehat Tbk. (MIKA)',
 'MINA.JK': 'Sanurhasta Mitra Tbk. (MINA)',
 'MIRA.JK': 'Mitra International Resources (MIRA)',
 'MITI.JK': 'Mitra Investindo Tbk. (MITI)',
 'MKNT.JK': 'Mitra Komunikasi Nusantara Tbk (MKNT)',
 'MKPI.JK': 'Metropolitan Kentjana Tbk. (MKPI)',
 'MLBI.JK': 'Multi Bintang Indonesia Tbk. (MLBI)',
 'MLIA.JK': 'Mulia Industrindo Tbk (MLIA)',
 'MLPL.JK': 'Multipolar Tbk. (MLPL)',
 'MLPT.JK': 'Multipolar Technology Tbk. (MLPT)',
 'MMLP.JK': 'Mega Manunggal Property Tbk. (MMLP)',
 'MNCN.JK': 'Media Nusantara Citra Tbk. (MNCN)',
 'MOLI.JK': 'Madusari Murni Indah Tbk. (MOLI)',
 'MPMX.JK': 'Mitra Pinasthika Mustika Tbk. (MPMX)',
 'MPOW.JK': 'Megapower Makmur Tbk. (MPOW)',
 'MPPA.JK': 'Matahari Putra Prima Tbk. (MPPA)',
 'MPRO.JK': 'Maha Properti Indonesia Tbk. (MPRO)',
 'MRAT.JK': 'Mustika Ratu Tbk. (MRAT)',
 'MREI.JK': 'Maskapai Reasuransi Indonesia (MREI)',
 'MSIN.JK': 'MNC Studios International Tbk. (MSIN)',
 'MSKY.JK': 'MNC Sky Vision Tbk. (MSKY)',
 'MTDL.JK': 'Metrodata Electronics Tbk. (MTDL)',
 'MTEL.JK': 'Dayamitra Telekomunikasi Tbk. (MTEL)',
 'MTFN.JK': 'Capitalinc Investment Tbk. (MTFN)',
 'MTLA.JK': 'Metropolitan Land Tbk. (MTLA)',
 'MTPS.JK': 'Meta Epsi Tbk. (MTPS)',
 'MTRA.JK': 'Mitra Pemuda Tbk. (MTRA)',
 'MTSM.JK': 'Metro Realty Tbk. (MTSM)',
 'MTWI.JK': 'Malacca Trust Wuwungan Insuran (MTWI)',
 'MYOH.JK': 'Samindo Resources Tbk. (MYOH)',
 'MYOR.JK': 'Mayora Indah Tbk. (MYOR)',
 'MYRX.JK': 'Hanson International Tbk. (MYRX)',
 'MYTX.JK': 'Asia Pacific Investama Tbk. (MYTX)',
 'NASA.JK': 'Andalan Perkasa Abadi Tbk. (NASA)',
 'NASI.JK': 'Wahana Inti Makmur Tbk. (NASI)',
 'NATO.JK': 'Surya Permata Andalan Tbk. (NATO)',
 'NELY.JK': 'Pelayaran Nelly Dwi Putri Tbk. (NELY)',
 'NFCX.JK': 'NFC Indonesia Tbk. (NFCX)',
 'NICK.JK': 'Charnic Capital Tbk. (NICK)',
 'NICL.JK': 'PAM Mineral Tbk. (NICL)',
 'NIKL.JK': 'Pelat Timah Nusantara Tbk. (NIKL)',
 'NIPS.JK': 'Nipress Tbk. (NIPS)',
 'NIRO.JK': 'City Retail Developments Tbk. (NIRO)',
 'NISP.JK': 'Bank OCBC NISP Tbk. (NISP)',
 'NOBU.JK': 'Bank Nationalnobu Tbk. (NOBU)',
 'NPGF.JK': 'Nusa Palapa Gemilang Tbk. (NPGF)',
 'NRCA.JK': 'Nusa Raya Cipta Tbk. (NRCA)',
 'NUSA.JK': 'Sinergi Megah Internusa Tbk. (NUSA)',
 'NZIA.JK': 'Nusantara Almazia Tbk. (NZIA)',
 'OASA.JK': 'Protech Mitra Perkasa Tbk. (OASA)',
 'OBMD.JK': 'OBM Drilchem Tbk. (OBMD)',
 'OCAP.JK': 'Onix Capital Tbk. (OCAP)',
 'OILS.JK': 'Indo Oil Perkasa Tbk. (OILS)',
 'OKAS.JK': 'Ancora Indonesia Resources Tbk (OKAS)',
 'OMRE.JK': 'Indonesia Prima Property Tbk (OMRE)',
 'OPMS.JK': 'Optima Prima Metal Sinergi Tbk (OPMS)',
 'PADI.JK': 'Minna Padi Investama Sekuritas (PADI)',
 'PALM.JK': 'Provident Agro Tbk. (PALM)',
 'PAMG.JK': 'Bima Sakti Pertiwi Tbk. (PAMG)',
 'PANI.JK': 'Pratama Abadi Nusa Industri Tb (PANI)',
 'PANR.JK': 'Panorama Sentrawisata Tbk. (PANR)',
 'PANS.JK': 'Panin Sekuritas Tbk. (PANS)',
 'PBID.JK': 'Panca Budi Idaman Tbk. (PBID)',
 'PBRX.JK': 'Pan Brothers Tbk. (PBRX)',
 'PBSA.JK': 'Paramita Bangun Sarana Tbk. (PBSA)',
 'PCAR.JK': 'Prima Cakrawala Abadi Tbk. (PCAR)',
 'PDES.JK': 'Destinasi Tirta Nusantara Tbk (PDES)',
 'PEGE.JK': 'Panca Global Kapital Tbk. (PEGE)',
 'PEHA.JK': 'Phapros Tbk. (PEHA)',
 'PGAS.JK': 'Perusahaan Gas Negara Tbk. (PGAS)',
 'PGJO.JK': 'Tourindo Guide Indonesia Tbk. (PGJO)',
 'PGLI.JK': 'Pembangunan Graha Lestari Inda (PGLI)',
 'PGUN.JK': 'Pradiksi Gunatama Tbk. (PGUN)',
 'PICO.JK': 'Pelangi Indah Canindo Tbk (PICO)',
 'PJAA.JK': 'Pembangunan Jaya Ancol Tbk. (PJAA)',
 'PKPK.JK': 'Perdana Karya Perkasa Tbk (PKPK)',
 'PLAN.JK': 'Planet Properindo Jaya Tbk. (PLAN)',
 'PLAS.JK': 'Polaris Investama Tbk (PLAS)',
 'PLIN.JK': 'Plaza Indonesia Realty Tbk. (PLIN)',
 'PMJS.JK': 'Putra Mandiri Jembar Tbk. (PMJS)',
 'PMMP.JK': 'Panca Mitra Multiperdana Tbk. (PMMP)',
 'PNBN.JK': 'Bank Pan Indonesia Tbk (PNBN)',
 'PNBS.JK': 'Bank Panin Dubai Syariah Tbk. (PNBS)',
 'PNGO.JK': 'Pinago Utama Tbk. (PNGO)',
 'PNIN.JK': 'Paninvest Tbk. (PNIN)',
 'PNLF.JK': 'Panin Financial Tbk. (PNLF)',
 'PNSE.JK': 'Pudjiadi & Sons Tbk. (PNSE)',
 'POLA.JK': 'Pool Advista Finance Tbk. (POLA)',
 'POLI.JK': 'Pollux Hotels Group Tbk. (POLI)',
 'POLL.JK': 'Pollux Properties Indonesia Tb (POLL)',
 'POLU.JK': 'Golden Flower Tbk. (POLU)',
 'POLY.JK': 'Asia Pacific Fibers Tbk (POLY)',
 'POOL.JK': 'Pool Advista Indonesia Tbk. (POOL)',
 'PORT.JK': 'Nusantara Pelabuhan Handal Tbk (PORT)',
 'POSA.JK': 'Bliss Properti Indonesia Tbk. (POSA)',
 'POWR.JK': 'Cikarang Listrindo Tbk. (POWR)',
 'PPGL.JK': 'Prima Globalindo Logistik Tbk. (PPGL)',
 'PPRE.JK': 'PP Presisi Tbk. (PPRE)',
 'PPRO.JK': 'PP Properti Tbk. (PPRO)',
 'PRAS.JK': 'Prima Alloy Steel Universal Tb (PRAS)',
 'PRDA.JK': 'Prodia Widyahusada Tbk. (PRDA)',
 'PRIM.JK': 'Royal Prima Tbk. (PRIM)',
 'PSAB.JK': 'J Resources Asia Pasifik Tbk. (PSAB)',
 'PSDN.JK': 'Prasidha Aneka Niaga Tbk (PSDN)',
 'PSGO.JK': 'Palma Serasih Tbk. (PSGO)',
 'PSKT.JK': 'Red Planet Indonesia Tbk. (PSKT)',
 'PSSI.JK': 'Pelita Samudera Shipping Tbk. (PSSI)',
 'PTBA.JK': 'Bukit Asam Tbk. (PTBA)',
 'PTDU.JK': 'Djasa Ubersakti Tbk. (PTDU)',
 'PTIS.JK': 'Indo Straits Tbk. (PTIS)',
 'PTPP.JK': 'PP (Persero) Tbk. (PTPP)',
 'PTPW.JK': 'Pratama Widya Tbk. (PTPW)',
 'PTRO.JK': 'Petrosea Tbk. (PTRO)',
 'PTSN.JK': 'Sat Nusapersada Tbk (PTSN)',
 'PTSP.JK': 'Pioneerindo Gourmet Internatio (PTSP)',
 'PUDP.JK': 'Pudjiadi Prestige Tbk. (PUDP)',
 'PURA.JK': 'Putra Rajawali Kencana Tbk. (PURA)',
 'PURE.JK': 'Trinitan Metals and Minerals T (PURE)',
 'PURI.JK': 'Puri Global Sukses Tbk. (PURI)',
 'PWON.JK': 'Pakuwon Jati Tbk. (PWON)',
 'PYFA.JK': 'Pyridam Farma Tbk (PYFA)',
 'PZZA.JK': 'Sarimelati Kencana Tbk. (PZZA)',
 'RAJA.JK': 'Rukun Raharja Tbk. (RAJA)',
 'RALS.JK': 'Ramayana Lestari Sentosa Tbk. (RALS)',
 'RANC.JK': 'Supra Boga Lestari Tbk. (RANC)',
 'RBMS.JK': 'Ristia Bintang Mahkotasejati T (RBMS)',
 'RDTX.JK': 'Roda Vivatex Tbk (RDTX)',
 'REAL.JK': 'Repower Asia Indonesia Tbk. (REAL)',
 'RELI.JK': 'Reliance Sekuritas Indonesia T (RELI)',
 'RICY.JK': 'Ricky Putra Globalindo Tbk (RICY)',
 'RIGS.JK': 'Rig Tenders Indonesia Tbk. (RIGS)',
 'RIMO.JK': 'Rimo International Lestari Tbk (RIMO)',
 'RISE.JK': 'Jaya Sukses Makmur Sentosa Tbk (RISE)',
 'RMBA.JK': 'Bentoel Internasional Investam (RMBA)',
 'RMKE.JK': 'RMK Energy Tbk. (RMKE)',
 'ROCK.JK': 'Rockfields Properti Indonesia (ROCK)',
 'RODA.JK': 'Pikko Land Development Tbk. (RODA)',
 'RONY.JK': 'Aesler Grup Internasional Tbk. (RONY)',
 'ROTI.JK': 'Nippon Indosari Corpindo Tbk. (ROTI)',
 'RSGK.JK': 'Kedoya Adyaraya Tbk. (RSGK)',
 'RUIS.JK': 'Radiant Utama Interinsco Tbk. (RUIS)',
 'RUNS.JK': 'Global Sukses Solusi Tbk. (RUNS)',
 'SAFE.JK': 'Steady Safe Tbk (SAFE)',
 'SAME.JK': 'Sarana Meditama Metropolitan T (SAME)',
 'SAMF.JK': 'Saraswanti Anugerah Makmur Tbk (SAMF)',
 'SAPX.JK': 'Satria Antaran Prima Tbk. (SAPX)',
 'SATU.JK': 'Kota Satu Properti Tbk. (SATU)',
 'SBAT.JK': 'Sejahtera Bintang Abadi Textil (SBAT)',
 'SBMA.JK': 'Surya Biru Murni Acetylene Tbk (SBMA)',
 'SCCO.JK': 'Supreme Cable Manufacturing & (SCCO)',
 'SCMA.JK': 'Surya Citra Media Tbk. (SCMA)',
 'SCNP.JK': 'Selaras Citra Nusantara Perkas (SCNP)',
 'SCPI.JK': 'Organon Pharma Indonesia Tbk. (SCPI)',
 'SDMU.JK': 'Sidomulyo Selaras Tbk. (SDMU)',
 'SDPC.JK': 'Millennium Pharmacon Internati (SDPC)',
 'SDRA.JK': 'Bank Woori Saudara Indonesia 1 (SDRA)',
 'SFAN.JK': 'Surya Fajar Capital Tbk. (SFAN)',
 'SGER.JK': 'Sumber Global Energy Tbk. (SGER)',
 'SGRO.JK': 'Sampoerna Agro Tbk. (SGRO)',
 'SHID.JK': 'Hotel Sahid Jaya International (SHID)',
 'SHIP.JK': 'Sillo Maritime Perdana Tbk. (SHIP)',
 'SIDO.JK': 'Industri Jamu dan Farmasi Sido (SIDO)',
 'SILO.JK': 'Siloam International Hospitals (SILO)',
 'SIMA.JK': 'Siwani Makmur Tbk (SIMA)',
 'SIMP.JK': 'Salim Ivomas Pratama Tbk. (SIMP)',
 'SINI.JK': 'Singaraja Putra Tbk. (SINI)',
 'SIPD.JK': 'Sreeya Sewu Indonesia Tbk. (SIPD)',
 'SKBM.JK': 'Sekar Bumi Tbk. (SKBM)',
 'SKLT.JK': 'Sekar Laut Tbk. (SKLT)',
 'SKRN.JK': 'Superkrane Mitra Utama Tbk. (SKRN)',
 'SKYB.JK': 'Northcliff Citranusa Indonesia (SKYB)',
 'SLIS.JK': 'Gaya Abadi Sempurna Tbk. (SLIS)',
 'SMAR.JK': 'Smart Tbk. (SMAR)',
 'SMBR.JK': 'Semen Baturaja (Persero) Tbk. (SMBR)',
 'SMCB.JK': 'Solusi Bangun Indonesia Tbk. (SMCB)',
 'SMDM.JK': 'Suryamas Dutamakmur Tbk. (SMDM)',
 'SMDR.JK': 'Samudera Indonesia Tbk. (SMDR)',
 'SMGR.JK': 'Semen Indonesia (Persero) Tbk. (SMGR)',
 'SMKL.JK': 'Satyamitra Kemas Lestari Tbk. (SMKL)',
 'SMMA.JK': 'Sinarmas Multiartha Tbk. (SMMA)',
 'SMMT.JK': 'Golden Eagle Energy Tbk. (SMMT)',
 'SMRA.JK': 'Summarecon Agung Tbk. (SMRA)',
 'SMRU.JK': 'SMR Utama Tbk. (SMRU)',
 'SMSM.JK': 'Selamat Sempurna Tbk. (SMSM)',
 'SNLK.JK': 'Sunter Lakeside Hotel Tbk. (SNLK)',
 'SOCI.JK': 'Soechi Lines Tbk. (SOCI)',
 'SOFA.JK': 'Boston Furniture Industries Tb (SOFA)',
 'SOHO.JK': 'Soho Global Health Tbk. (SOHO)',
 'SONA.JK': 'Sona Topas Tourism Industry Tb (SONA)',
 'SOSS.JK': 'Shield On Service Tbk. (SOSS)',
 'SOTS.JK': 'Satria Mega Kencana Tbk. (SOTS)',
 'SPMA.JK': 'Suparma Tbk. (SPMA)',
 'SPTO.JK': 'Surya Pertiwi Tbk. (SPTO)',
 'SQMI.JK': 'Wilton Makmur Indonesia Tbk. (SQMI)',
 'SRAJ.JK': 'Sejahteraraya Anugrahjaya Tbk. (SRAJ)',
 'SRIL.JK': 'Sri Rejeki Isman Tbk. (SRIL)',
 'SRSN.JK': 'Indo Acidatama Tbk (SRSN)',
 'SRTG.JK': 'Saratoga Investama Sedaya Tbk. (SRTG)',
 'SSIA.JK': 'Surya Semesta Internusa Tbk. (SSIA)',
 'SSMS.JK': 'Sawit Sumbermas Sarana Tbk. (SSMS)',
 'SSTM.JK': 'Sunson Textile Manufacture Tbk (SSTM)',
 'STAR.JK': 'Buana Artha Anugerah Tbk. (STAR)',
 'STTP.JK': 'Siantar Top Tbk. (STTP)',
 'SUGI.JK': 'Sugih Energy Tbk. (SUGI)',
 'SULI.JK': 'SLJ Global Tbk. (SULI)',
 'SUPR.JK': 'Solusi Tunas Pratama Tbk. (SUPR)',
 'SURE.JK': 'Super Energy Tbk. (SURE)',
 'SWAT.JK': 'Sriwahana Adityakarta Tbk. (SWAT)',
 'TALF.JK': 'Tunas Alfin Tbk. (TALF)',
 'TAMA.JK': 'Lancartama Sejati Tbk. (TAMA)',
 'TAMU.JK': 'Pelayaran Tamarin Samudra Tbk. (TAMU)',
 'TAPG.JK': 'Triputra Agro Persada Tbk. (TAPG)',
 'TARA.JK': 'Agung Semesta Sejahtera Tbk. (TARA)',
 'TAXI.JK': 'Express Transindo Utama Tbk. (TAXI)',
 'TAYS.JK': 'Jaya Swarasa Agung Tbk. (TAYS)',
 'TBIG.JK': 'Tower Bersama Infrastructure T (TBIG)',
 'TBLA.JK': 'Tunas Baru Lampung Tbk. (TBLA)',
 'TBMS.JK': 'Tembaga Mulia Semanan Tbk. (TBMS)',
 'TCID.JK': 'Mandom Indonesia Tbk. (TCID)',
 'TCPI.JK': 'Transcoal Pacific Tbk. (TCPI)',
 'TDPM.JK': 'Tridomain Performance Material (TDPM)',
 'TEBE.JK': 'Dana Brata Luhur Tbk. (TEBE)',
 'TECH.JK': 'Indosterling Technomedia Tbk. (TECH)',
 'TELE.JK': 'Tiphone Mobile Indonesia Tbk. (TELE)',
 'TFAS.JK': 'Telefast Indonesia Tbk. (TFAS)',
 'TFCO.JK': 'Tifico Fiber Indonesia Tbk. (TFCO)',
 'TGKA.JK': 'Tigaraksa Satria Tbk. (TGKA)',
 'TGRA.JK': 'Terregra Asia Energy Tbk. (TGRA)',
 'TIFA.JK': 'KDB Tifa Finance Tbk. (TIFA)',
 'TINS.JK': 'Timah Tbk. (TINS)',
 'TIRA.JK': 'Tira Austenite Tbk (TIRA)',
 'TIRT.JK': 'Tirta Mahakam Resources Tbk (TIRT)',
 'TKIM.JK': 'Pabrik Kertas Tjiwi Kimia Tbk. (TKIM)',
 'TLKM.JK': 'Telkom Indonesia (Persero) Tbk (TLKM)',
 'TMAS.JK': 'Temas Tbk. (TMAS)',
 'TMPO.JK': 'Tempo Intimedia Tbk. (TMPO)',
 'TNCA.JK': 'Trimuda Nuansa Citra Tbk. (TNCA)',
 'TOBA.JK': 'TBS Energi Utama Tbk. (TOBA)',
 'TOPS.JK': 'Totalindo Eka Persada Tbk. (TOPS)',
 'TOTL.JK': 'Total Bangun Persada Tbk. (TOTL)',
 'TOTO.JK': 'Surya Toto Indonesia Tbk. (TOTO)',
 'TOWR.JK': 'Sarana Menara Nusantara Tbk. (TOWR)',
 'TOYS.JK': 'Sunindo Adipersada Tbk. (TOYS)',
 'TPIA.JK': 'Chandra Asri Petrochemical Tbk (TPIA)',
 'TPMA.JK': 'Trans Power Marine Tbk. (TPMA)',
 'TRAM.JK': 'Trada Alam Minera Tbk. (TRAM)',
 'TRIL.JK': 'Triwira Insanlestari Tbk. (TRIL)',
 'TRIM.JK': 'Trimegah Sekuritas Indonesia T (TRIM)',
 'TRIN.JK': 'Perintis Triniti Properti Tbk. (TRIN)',
 'TRIO.JK': 'Trikomsel Oke Tbk. (TRIO)',
 'TRIS.JK': 'Trisula International Tbk. (TRIS)',
 'TRJA.JK': 'Transkon Jaya Tbk. (TRJA)',
 'TRST.JK': 'Trias Sentosa Tbk. (TRST)',
 'True.JK': 'Triniti Dinamik Tbk. (True)',
 'TRUK.JK': 'Guna Timur Raya Tbk. (TRUK)',
 'TRUS.JK': 'Trust Finance Indonesia Tbk (TRUS)',
 'TSPC.JK': 'Tempo Scan Pacific Tbk. (TSPC)',
 'TUGU.JK': 'Asuransi Tugu Pratama Indonesi (TUGU)',
 'TURI.JK': 'Tunas Ridean Tbk. (TURI)',
 'UANG.JK': 'Pakuan Tbk. (UANG)',
 'UCID.JK': 'Uni-Charm Indonesia Tbk. (UCID)',
 'UFOE.JK': 'Damai Sejahtera Abadi Tbk. (UFOE)',
 'ULTJ.JK': 'Ultra Jaya Milk Industry & Tra (ULTJ)',
 'UNIC.JK': 'Unggul Indah Cahaya Tbk. (UNIC)',
 'UNIQ.JK': 'Ulima Nitra Tbk. (UNIQ)',
 'UNIT.JK': 'Nusantara Inti Corpora Tbk (UNIT)',
 'UNSP.JK': 'Bakrie Sumatera Plantations Tb (UNSP)',
 'UNTR.JK': 'United Tractors Tbk. (UNTR)',
 'UNVR.JK': 'Unilever Indonesia Tbk. (UNVR)',
 'URBN.JK': 'Urban Jakarta Propertindo Tbk. (URBN)',
 'UVCR.JK': 'Trimegah Karya Pratama Tbk. (UVCR)',
 'VICI.JK': 'Victoria Care Indonesia Tbk. (VICI)',
 'VICO.JK': 'Victoria Investama Tbk. (VICO)',
 'VINS.JK': 'Victoria Insurance Tbk. (VINS)',
 'VIVA.JK': 'Visi Media Asia Tbk. (VIVA)',
 'VOKS.JK': 'Voksel Electric Tbk. (VOKS)',
 'VRNA.JK': 'Verena Multi Finance Tbk. (VRNA)',
 'WAPO.JK': 'Wahana Pronatural Tbk. (WAPO)',
 'WEGE.JK': 'Wijaya Karya Bangunan Gedung T (WEGE)',
 'WEHA.JK': 'WEHA Transportasi Indonesia Tb (WEHA)',
 'WGSH.JK': 'Wira Global Solusi Tbk. (WGSH)',
 'WICO.JK': 'Wicaksana Overseas Internation (WICO)',
 'WIFI.JK': 'Solusi Sinergi Digital Tbk. (WIFI)',
 'WIIM.JK': 'Wismilak Inti Makmur Tbk. (WIIM)',
 'WIKA.JK': 'Wijaya Karya (Persero) Tbk. (WIKA)',
 'WINS.JK': 'Wintermar Offshore Marine Tbk. (WINS)',
 'WMPP.JK': 'Widodo Makmur Perkasa Tbk. (WMPP)',
 'WMUU.JK': 'Widodo Makmur Unggas Tbk. (WMUU)',
 'WOMF.JK': 'Wahana Ottomitra Multiartha Tb (WOMF)',
 'WOOD.JK': 'Integra Indocabinet Tbk. (WOOD)',
 'WOWS.JK': 'Ginting Jaya Energi Tbk. (WOWS)',
 'WSBP.JK': 'Waskita Beton Precast Tbk. (WSBP)',
 'WSKT.JK': 'Waskita Karya (Persero) Tbk. (WSKT)',
 'WTON.JK': 'Wijaya Karya Beton Tbk. (WTON)',
 'YELO.JK': 'Yelooo Integra Datanet Tbk. (YELO)',
 'YPAS.JK': 'Yanaprima Hastapersada Tbk (YPAS)',
 'YULE.JK': 'Yulie Sekuritas Indonesia Tbk. (YULE)',
 'ZBRA.JK': 'Zebra Nusantara Tbk (ZBRA)',
 'ZINC.JK': 'Kapuas Prima Coal Tbk. (ZINC)',
 'ZONE.JK': 'Mega Perintis Tbk. (ZONE)',
 'ZYRX.JK': 'Zyrexindo Mandiri Buana Tbk. (ZYRX)'}